name: Unit Tests

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*.*.*'
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm 8
        run: |
          npm install --location=global npm@8
      - name: Install dependencies
        run: |
          npm install
        env:
          CI: true

      - name: Build for Node.js ${{ matrix.node-version }}
        run: |
          npm run build

      - name: Unit tests
        run: |
          npm run test
        env:
          CI: true
